### ISSUE TITLE
Is s3 rm --recursive supported?

### ISSUE THREAD

**Issue by eatmorelard** [hirose31/AWS-CLIWrapper#13]
I'm trying to delete all objects in a folder in s3 which I can do via the AWS CLI using the --recursive option for rm. Is it supported in the perl CLIWrapper? If so, how do I add the ''--recursive" option?

**Comment by hirose31** [comment]
try:

```perl
$aws->s3('rm', ['s3://yourbucket/path/to/dir'],
         {
             'recursive' => $AWS::CLIWrapper::true,
         });
```

**Comment by hirose31** [comment]
no response for a long time
