### ISSUE TITLE
aws s3 cp $x $y with --grants requires shell_quote to be optional

### ISSUE THREAD

**Issue by traveltek-mmacnair** [hirose31/AWS-CLIWrapper#17]
Hello!

The aws s3 cp --grants option allows for specific read/write/etc permissions to be assigned on a cannonical id basis, however to assign different permission levels on the same operation, it's necessary to separate the elements with a space; e.g. 

`aws s3 cp example.json s3://target-bucket --grants full=id=DEADBEEF read=id=B16BEEF`

At present, passing a grants structure with the above grants string will be auto quoted to 'full=id=DEADBEEF read=id=B16BEEF', and this will be rejected by the command line interpreter

A possible work around in line with how Sql::Abstract does it would be to permit string references as literal values.

**Comment by hirose31** [comment]
Could you try to pass grants by ArrayRef:

```pl
my $res = $aws->s3('cp', ['example.json' => 's3://target-bucket'], {
    'grants' => [
        'full=id=DEADBEEF',
        'read=id=CAFEBABE',
    ],
});
```

**Comment by traveltek-mmacnair** [comment]
Issue resolved as suggested.
