### ISSUE TITLE
AWS::CLIWrapper is missing on metacpan.org

### ISSUE THREAD

**Issue by nohuhu** [hirose31/AWS-CLIWrapper#21]
Not sure what the issue is, however searching for `AWS::CLIWrapper` produces no direct results: https://metacpan.org/search?size=20&q=AWS%3A%3ACLIWrapper

Trying to open the package pod page directly also doesn't work: https://metacpan.org/pod/AWS::CLIWrapper

Installing the package with cpanm works as expected:

```
~$ cpanm AWS::CLIWrapper
--> Working on AWS::CLIWrapper
Fetching http://www.cpan.org/authors/id/H/HI/HIROSE/AWS-CLIWrapper-1.25.tar.gz ... OK
Configuring AWS-CLIWrapper-1.25 ... OK
Building and testing AWS-CLIWrapper-1.25 ... OK
Successfully installed AWS-CLIWrapper-1.25 (upgraded from 1.23)
1 distribution installed
```

**Comment by hirose31** [comment]
I just tried it and it was fine, so I'll close it.
