### ISSUE TITLE
sdb is available in preview mode for the aws cli commands but isn't in the wrapper

### ISSUE THREAD

**Issue by efreedom79** [hirose31/AWS-CLIWrapper#6]
This error 

Can't locate object method "sdb" via package "AWS::CLIWrapper" at ./sdbRequest line 7.

is returned when I try to execute this:

$aws->sdb('put-attributes',
          {
              domain-name => 'asg-store',
              item-name => 'my-third-asg-item',
              attribute => {Name => "capacity",Value => "1/5/3"}
          });

**Comment by hirose31** [comment]
no response for a long time
